### PR TITLE
README.md - YouTube link for video 3

### PR DESCRIPTION
**Pull request by koolhand**
Updated to YouTube for the 3rd video link, for consistency.

### CODE REVIEW

**Comment by JonasBK** [comment]
Hi @koolhand,

Thanks for the PR!

Can I get you to post a comment with the string: "I have read the CLA Document and I hereby sign the CLA"?
The CLA Document can be read here: https://github.com/BloodHoundAD/CLA/blob/main/ICLA.md

Cheers

**Comment by koolhand** [comment]
Sure!

**Comment by koolhand** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by JonasBK** [comment]
recheck

**Pull request merged**
